### ISSUE TITLE
APIリファレンスでは"checkCheckbox"ですがコードでは"checkCheckBox"になっています

### ISSUE THREAD

**Issue by IkeMkm** [goqoo-on-kintone/jinzo-ningen#30]
APIリファレンスでは"checkCheckbox"となっていましたが、実際のコードではBが大文字でcheckCheckBoxとなっている様です。
version: 1.1.0

**Comment by IkeMkm** [comment]
APIリファレンスでは"checkCheckbox"となっていましたが、実際のコードではBが大文字でcheckCheckBoxとなっている様です。

**Comment by latica-jp** [comment]
ご指摘のとおり、リファレンスが誤っておりましたので、修正いたしました。
https://github.com/goqoo-on-kintone/jinzo-ningen/blob/master/doc/reference.md#checkcheckboxfieldcode-itemcheckmap

ご報告ありがとうございました！
